completed interactive mode

diff --git a/centrunk_installer b/centrunk_installer
--- a/centrunk_installer
+++ b/centrunk_installer
@@ -19,9 +19,29 @@ clean_environment()
 {
     if [[ $DEBUG -eq 0 ]]
     then
-        rm -rf $INSTALL_LOC
-        rm -rf /opt/dvm-firmware/
-        write_log_event "Cleaned install directory $INSTALL_LOC."
+        read -p "This installer will REMOVE any files located in the following directories:
+        * /opt/dvm
+        * /opt/dvmfirmware-hs
+        
+        Are you sure you want to continue? [Y/N]: " resp2
+        case $resp2 in
+            Y | y)
+              write_log_event "User has elected to continue."
+              rm -rf $INSTALL_LOC
+              rm -rf /opt/dvmfirmware-hs/
+              write_log_event "Cleaned install directory $INSTALL_LOC."
+              ;;
+            N | n)
+              write_log_event "User has elected to exit."
+              echo "Stopping install...Nothing was changed."
+              exit 42
+              ;;
+            *)
+              write_log_event "Invalid entry, displaying help to user."
+              usage
+              exit 96
+              ;;
+        esac
     fi
 }
 
@@ -74,6 +94,151 @@ usage()
     --help]
     | [--interactive]
     "
+}
+
+install_centrunk()
+{
+  write_log_event "Actually starting the install now!"
+  sleep 1
+  echo "You may see a bunch of shit you may or may not recognize
+  Don't worry about it. It's the program installing and creating itself. Woo!"
+  sleep 3
+
+  clean_environment
+
+  cd $BASE_DIR
+
+  write_log_event "Cloning DVMhost from GitHub..."
+  git clone $GIT_URL $INSTALL_LOC
+
+  cd $INSTALL_LOC
+
+  #build the boi
+
+  write_log_event "Building dvmhost..."
+  echo "Building DVMhost...this may take some time..."
+  make
+
+  #fixup perms
+  write_log_event "Permissions updating..."
+  chmod +x start-dvm.sh stop-dvm.sh dvm-watchdog.sh stop-watchdog.sh
+
+  #install default configs from git
+
+  write_log_event "Checking out default configurations from GitHub..."
+  git clone $CONFIG_REPO $CONFIG_DIR
+
+  #handle config based on responsess
+
+  case $TYPE in
+      VOICE)
+        cp $CONFIG_DIR/ct-vc.yml $INSTALL_LOC/config.centrunk.yml
+        replace_config "$INSTALL_LOC/config.centrunk.yml"
+        ;;
+      CONTROL)
+        cp $CONFIG_DIR/ct-cc-dedicated.yml $INSTALL_LOC/config.centrunk.yml
+        replace_config "$INSTALL_LOC/config.centrunk.yml"
+        ;;
+      VOC)
+        cp $CONFIG_DIR/ct-voc.yml $INSTALL_LOC/config.centrunk.yml
+        replace_config "$INSTALL_LOC/config.centrunk.yml"
+        ;;
+      *)
+        write_log_event "User has somehow gotten to a place they shouldn't. See code, line 279."
+        echo "How did you get here?"
+        exit 69
+        ;;
+  esac
+
+
+
+  #install the unit file
+
+  write_log_event "Installing the P25 systemd Service..."
+  
+  if [[ -f /etc/systemd/system/centrunk.service ]]
+  then
+    systemctl stop centrunk.service
+    systemctl disable centrunk.service
+    rm -rf /etc/systemd/system/centrunk.service
+  fi
+
+  cp $CONFIG_DIR/p25.service /etc/systemd/system/centrunk.service
+  write_log_event "Updating permissions on the Service..."
+  chmod 664 /etc/systemd/system/centrunk.service
+  systemctl daemon-reload
+  write_log_event ""
+  systemctl enable centrunk.service
+  #output commands
+  write_log_event "!!!DVMhost install completed.!!!"
+  echo "Done installing DVMhost."
+
+  # ollie outie if we aren't flashing
+  if [[ $FLASH -ne 1 ]]
+  then
+      write_log_event "Not flashing the modem per user input...Quitting..."
+      echo "Not flashing the modem...exiting..."
+      exit 0
+  else
+      write_log_event "Flashing the modem."
+      echo "Flashing the modem. Please standby while we gather some files..."    
+  fi
+
+  write_log_event "Entering the Firmware Block..."
+  ###### FIRMWARE BLOCK #####
+  #clone out the firmware and tools
+  write_log_event "Cloning firmware from GitHub..."
+  cd /opt
+  git clone $FW_GIT_URL
+  cd /opt/dvmfirmware-hs/
+  git clone $FW_TOOLS_F10X
+
+  write_log_event "Starting the firmware build process..."
+  #build the firmware
+  echo "Building the firmware in 5 seconds..."
+  sleep 5
+  make -f Makefile.STM32FX mmdvm-hs-hat-dual
+  write_log_event "Firmware build completed!"
+
+  #flash the firmware
+  write_log_event "About to flash the firmware...asking for consent..."
+  read -p "FLASHING THE FIRMWARE NOW. DO YOU WANT TO CONTINUE? [Y/N]: " flashing
+  case $flashing in
+      Y|y)
+        write_log_event "User has elected to flash firmware...Proceeding..."
+        echo "FLASHING NOW. DO NOT REMOVE POWER!"
+        if [[ -f dvm-firmware-hs_f1.bin ]]
+          then
+          stm32flash -v -w dvm-firmware-hs_f1.bin -i 20,-21,21,-20 -R $PATH_TO_MODEM -b 115200
+          write_log_event "Flash completed..."
+        fi
+        ;;
+      N|n)
+        write_log_event "User has elected to abort..."
+        echo "Aborting flash, but continuing..."
+  esac
+
+  write_log_event "Done with Flash Block..."
+
+  ##### ZEROTIER BLOCK #####
+
+  write_log_event "Entering zerotier installation..."
+
+  write_log_event "Ensuring ZeroTier is installed..."
+  if [ -x "$(command -v zerotier-cli)" ]
+  then
+      write_log_event "ZeroTier is already installed, joining the network..."
+      zerotier-cli join $ZEROTIER
+  else
+      write_log_event "ZeroTier is not installed, installing now..."
+      curl -s https://install.zerotier.com/ | bash
+      zerotier-cli join $ZEROTIER
+  fi
+
+  echo "Everything should be done installing...\\n\\nTo start dvmhost, run \"sudo systemctl start centrunk.service\""
+  exit 0
+
+  
 }
 
 echo "Welcome to the Centrunk Installer." 
@@ -248,6 +413,7 @@ then
                     esac
 
                 done
+            break
             ;;
             *)
                 continue        
@@ -262,10 +428,6 @@ then
     read -p "Then, I'll need the FNE's IP address. Ask for this in Discord. : " IP_ADDRESS
 
     read -p "Next, I'll need to know the location of your modem: " PATH_TO_MODEM
-
-    read -p "After that, I'll need your RX Freqency: " RX_FREQ
-
-    read -p "Now I need your TX Frequency: " TX_FREQ
 
     echo "Okay, just a few more, I promise..."
 
@@ -304,204 +466,95 @@ then
 
     echo "Please wait while the hamster wheels are turning..."
 
-    echo "Thank you for trying Interactive Mode Beta. Please leave feedback on Discord."
+    echo "Just a few more questions, then we'll on our way!"
 
-    exit 0
+    read -p "Select the following from the menu
+    
+    [0]: 800 MHz
+    [1]: 700 MHz
+    [2]: 420-470 MHz (UHF)
+    [3]: 136-174 MHz (VHF)
+    [15]: 900 MHz
+    
+    Your response: " CID
 
-    # calculate channel id from tx frequency
+    read -p "RCON Port (You'll get this from Discord): " RCON_PORT
+
+    echo "The next two you will need to have calculated based on your hotspot's TX/RX frequency."
+
+    read -p "Channel ID: " CHID
+
+    read -p "Voice Channel: " VCN
 
     # prompt for channel number and voice channel number
 
     # prompt for RCON port
-
+    read -p "Last one! Equipment ID: " EQUIP_ID
     # prompt for equipment ID
 
+    echo "Alright we're done gathering information. Please sit back and relax while we set everything up for you."
+
+else
+  echo \
+  "TYPE=$TYPE
+  ZT=$ZEROTIER
+  EQUIP_ID=$EQUIP_ID
+  IP_ADDRESS=$IP_ADDRESS
+  RCON_PORT=$RCON_PORT
+  UART=$PATH_TO_MODEM
+  CHANNEL=$CID
+  RFSS_ID=$RFSS_ID
+  SITE_ID=$SITE_ID
+  SYS_ID=$SYS_ID
+  NET_ID=$NET_ID
+  NAC=$NAC_CODE
+  ATG=$SUPER_GROUP
+  FLASH=$FLASH
+  CHANNELID=$CHID
+  VOICECHANNEL=$VCN"
+
+  write_log_event \
+  "TYPE=$TYPE\n
+  ZT=$ZEROTIER\n
+  EQUIP_ID=$EQUIP_ID\n
+  IP_ADDRESS=$IP_ADDRESS\n
+  RCON_PORT=$RCON_PORT\n
+  UART=$PATH_TO_MODEM\n
+  CHANNEL=$CID\n
+  RFSS_ID=$RFSS_ID\n
+  SITE_ID=$SITE_ID\n
+  SYS_ID=$SYS_ID\n
+  NET_ID=$NET_ID\n
+  NAC=$NAC_CODE\n
+  ATG=$SUPER_GROUP\n
+  FLASH=$FLASH\n\n
+  CHANNELID=$CHID
+  VOICECHANNEL=$VCN"
+
+
+
+  read -p "Are these values correct? [Y/N]: " resp2
+
+  case $resp2 in
+      Y | y)
+        write_log_event "User has elected to continue."
+        ;;
+      N | n)
+        write_log_event "User has elected to exit."
+        exit 96
+        ;;
+      *)
+        write_log_event "Invalid entry, displaying help to user."
+        usage
+        exit 96
+        ;;
+  esac
+  ##### /VARIABLES #####
 fi
 
-
-echo \
-"TYPE=$TYPE
-ZT=$ZEROTIER
-EQUIP_ID=$EQUIP_ID
-IP_ADDRESS=$IP_ADDRESS
-RCON_PORT=$RCON_PORT
-UART=$PATH_TO_MODEM
-CHANNEL=$CID
-RFSS_ID=$RFSS_ID
-SITE_ID=$SITE_ID
-SYS_ID=$SYS_ID
-NET_ID=$NET_ID
-NAC=$NAC_CODE
-ATG=$SUPER_GROUP
-FLASH=$FLASH
-CHANNELID=$CHID
-VOICECHANNEL=$VCN"
-
-write_log_event \
-"TYPE=$TYPE\n
-ZT=$ZEROTIER\n
-EQUIP_ID=$EQUIP_ID\n
-IP_ADDRESS=$IP_ADDRESS\n
-RCON_PORT=$RCON_PORT\n
-UART=$PATH_TO_MODEM\n
-CHANNEL=$CID\n
-RFSS_ID=$RFSS_ID\n
-SITE_ID=$SITE_ID\n
-SYS_ID=$SYS_ID\n
-NET_ID=$NET_ID\n
-NAC=$NAC_CODE\n
-ATG=$SUPER_GROUP\n
-FLASH=$FLASH\n\n
-CHANNELID=$CHID
-VOICECHANNEL=$VCN"
-
-
-
-read -p "Are these values correct? [Y/N]: " resp2
-
-case $resp2 in
-    Y | y)
-      write_log_event "User has elected to continue."
-      ;;
-    N | n)
-      write_log_event "User has elected to exit."
-      exit 96
-      ;;
-    *)
-      write_log_event "Invalid entry, displaying help to user."
-      usage
-      exit 96
-      ;;
-esac
-##### /VARIABLES #####
+install_centrunk
 
 ##### DVM BLOCK #####
 
-write_log_event "Actually starting the install now!"
 
 
-clean_environment
-
-cd $BASE_DIR
-
-write_log_event "Cloning DVMhost from GitHub..."
-git clone $GIT_URL $INSTALL_LOC
-
-cd $INSTALL_LOC
-
-#build the boi
-
-write_log_event "Building dvmhost..."
-echo "Building DVMhost...this may take some time..."
-make
-
-#fixup perms
-write_log_event "Permissions updating..."
-chmod +x start-dvm.sh stop-dvm.sh dvm-watchdog.sh stop-watchdog.sh
-
-#install default configs from git
-
-write_log_event "Checking out default configurations from GitHub..."
-git clone $CONFIG_REPO $CONFIG_DIR
-
-#handle config based on responsess
-
-case $TYPE in
-    VOICE)
-      cp $CONFIG_DIR/ct-vc.yml $INSTALL_LOC/config.centrunk.yml
-      replace_config "$INSTALL_LOC/config.centrunk.yml"
-      ;;
-    CONTROL)
-      cp $CONFIG_DIR/ct-cc-dedicated.yml $INSTALL_LOC/config.centrunk.yml
-      replace_config "$INSTALL_LOC/config.centrunk.yml"
-      ;;
-    VOC)
-      cp $CONFIG_DIR/ct-voc.yml $INSTALL_LOC/config.centrunk.yml
-      replace_config "$INSTALL_LOC/config.centrunk.yml"
-      ;;
-    *)
-      write_log_event "User has somehow gotten to a place they shouldn't. See code, line 279."
-      echo "How did you get here?"
-      exit 69
-      ;;
-esac
-
-
-#install the unit file
-
-write_log_event "Installing the P25 systemd Service..."
-cp $CONFIG_DIR/p25.service /etc/systemd/system/p25.service
-write_log_event "Updating permissions on the Service..."
-chmod 664 /etc/systemd/system/p25.service
-systemctl daemon-reload
-
-#output commands
-write_log_event "!!!DVMhost install completed.!!!"
-echo "Done installing DVMhost."
-
-# ollie outie if we aren't flashing
-if [[ $FLASH -ne 1 ]]
-then
-    write_log_event "Not flashing the modem per user input...Quitting..."
-    echo "Not flashing the modem...exiting..."
-    exit 0
-else
-    write_log_event "Flashing the modem."
-    echo "Flashing the modem. Please standby while we gather some files..."    
-fi
-
-write_log_event "Entering the Firmware Block..."
-###### FIRMWARE BLOCK #####
-#clone out the firmware and tools
-write_log_event "Cloning firmware from GitHub..."
-cd /opt
-git clone $FW_GIT_URL
-cd /opt/dvmfirmware-hs/
-git clone $FW_TOOLS_F10X
-
-write_log_event "Starting the firmware build process..."
-#build the firmware
-echo "Building the firmware in 5 seconds..."
-sleep 5
-make -f Makefile.STM32FX mmdvm-hs-hat-dual
-write_log_event "Firmware build completed!"
-
-#flash the firmware
-write_log_event "About to flash the firmware...asking for consent..."
-read -p "FLASHING THE FIRMWARE NOW. DO YOU WANT TO CONTINUE? [Y/N]: " flashing
-case $flashing in
-    Y|y)
-      write_log_event "User has elected to flash firmware...Proceeding..."
-      echo "FLASHING NOW. DO NOT REMOVE POWER!"
-      if [[ -f dvm-firmware-hs_f1.bin ]]
-        then
-        stm32flash -v -w dvm-firmware-hs_f1.bin -i 20,-21,21,-20 -R $PATH_TO_MODEM -b 115200
-        write_log_event "Flash completed..."
-      fi
-      ;;
-    N|n)
-      write_log_event "User has elected to abort..."
-      echo "Aborting flash, but continuing..."
-esac
-
-write_log_event "Done with Flash Block..."
-
-##### ZEROTIER BLOCK #####
-
-write_log_event "Entering zerotier installation..."
-
-write_log_event "Ensuring ZeroTier is installed..."
-if [ -x "$(command -v zerotier-cli)" ]
-then
-    write_log_event "ZeroTier is already installed, joining the network..."
-    zerotier-cli join $ZEROTIER
-else
-    write_log_event "ZeroTier is not installed, installing now..."
-    curl -s https://install.zerotier.com/ | bash
-    zerotier-cli join $ZEROTIER
-fi
-
-
-
-echo "Everything should be done installing...\\n\\nTo start dvmhost, run \"sudo systemctl start p25.service\""
-exit 0
